apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-storage
  name: nginx-storage
spec:
  containers:
  - image: nginx
    name: nginx-storage
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox
    name: busybox 
    command: ["bin/sh", "-c"]
    args: ["sleep 1000"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi 
